#ifndef BACKUPSSH_ERROR_H
#define BACKUPSSH_ERROR_H

typedef enum {
	BACKUPSSH_SUCCESS = 0,
	BACKUPSSH_PUBKEY_ERR = 1,
	BACKUPSSH_HASH_ERR = 2,
	BACKUPSSH_HOST_KNOWN = 3,
	BACKUPSSH_HOST_UNKNOWN = 4,
} ssh_error;

#endif
