#ifndef BACKUPSSH_ERROR_H
#define BACKUPSSH_ERROR_H

typedef enum {
	BACKUPSSH_SUCCESS = 0,
	BACKUPSSH_PUBKEY_ERR = 1,
	BACKUPSSH_HASH_ERR = 2,
	BACKUPSSH_HOST_KNOWN = 3,
	BACKUPSSH_HOST_UNKNOWN = 4,
	BACKUPSSH_HOST_IP_CHANGED = 5,
	BACKUPSSH_HOST_HASH_CHANGED = 6,
	BACKUPSSH_FILE_OPEN_ERROR = 7,
} ssh_error;

#endif
