#ifndef BACKUPSSH_ERROR_H
#define BACKUPSSH_ERROR_H

typedef enum {
	BACKUPSSH_SUCCESS = 0,
	BACKUPSSH_PUBKEY_ERR = 1,
	BACKUPSSH_HASH_ERR = 2,
	BACKUPSSH_HOST_KNOWN = 3,
	BACKUPSSH_HOST_UNKNOWN = 4,
	BACKUPSSH_HOST_IP_CHANGED = 5,
	BACKUPSSH_HOST_HASH_CHANGED = 6,
	BACKUPSSH_FILE_OPEN_ERR = 7,
	BACKUPSSH_SESSION_CREATE = 8,
	BACKUPSSH_AUTH_ERR = 9,
	BACKUPSSH_PRIVKEY_ERR = 10,
} ssh_error;

#endif
